# Generated by Django 4.0.3 on 2022-06-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '作者基本情况',
                'verbose_name_plural': '作者基本情况',
            },
        ),
        migrations.CreateModel(
            name='publishing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='期刊名称')),
                ('IF_number', models.CharField(max_length=20, verbose_name='影响因子')),
                ('SCIE_choice', models.CharField(choices=[('SCI', 'SCI'), ('IE', 'IEEE'), ('SCIE', 'SCI&IEEE'), ('None', 'ALL NOT')], max_length=10)),
            ],
            options={
                'verbose_name': '期刊信息',
                'verbose_name_plural': '期刊信息',
            },
        ),
        migrations.CreateModel(
            name='papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文献名称')),
                ('TypeofPaper', models.TextField(verbose_name='文献类型')),
                ('SpaceofPaper', models.TextField(verbose_name='研究邻域')),
                ('basement_message', models.CharField(max_length=30, verbose_name='摘要')),
                ('keyword', models.TextField(verbose_name='keyword')),
                ('paper_link', models.TextField(verbose_name='DOI')),
                ('Code_link', models.TextField(verbose_name='Github')),
                ('publish_date', models.DateField(verbose_name='接收时间')),
                ('author', models.ManyToManyField(to='papers.author', verbose_name='作者')),
                ('publishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.publishing', verbose_name='期刊名称')),
            ],
            options={
                'verbose_name': '文献信息',
                'verbose_name_plural': '文献信息',
            },
        ),
    ]
