# Generated by Django 4.0.3 on 2022-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_author_name_alter_papers_basement_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='basement_message',
            field=models.TextField(verbose_name='摘要'),
        ),
    ]
