# Generated by Django 4.0.3 on 2022-06-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_alter_papers_basement_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='SpaceofPaper',
            new_name='Space_ofPaper',
        ),
    ]
